
-- Converts a date/timestamp/string to a value of string in the format specified by the date format given by the second argument.
CREATE OR REPLACE FUNCTION DATE_FORMAT(DATE_VALUE DATE,FORMAT STRING) RETURNS STRING
AS $$
  TO_CHAR(DATE_VALUE, FORMAT)
$$


CREATE OR REPLACE FUNCTION DATE_FORMAT(DATE_VALUE TIMESTAMP,FORMAT STRING) RETURNS STRING
AS $$
  TO_CHAR(DATE_VALUE, FORMAT)
$$


CREATE OR REPLACE FUNCTION DATE_FORMAT(DATE_VALUE STRING,FORMAT STRING) RETURNS STRING
AS $$
  TO_CHAR(TRY_CAST(DATE_VALUE AS TIMESTAMP), FORMAT)
$$
